language: node_js
node_js:
  - "8"
install:
  - npm install
deploy:
  provider: npm
  email: tastee.is.good@gmail.com
  api_key:
    secure: cvC6AjDMNLXnkQaPGT3TiOqKkviusZcpMZnBBe5KqgVIvw0Dsj41Fy9sO2PwqvgJ0b153irYE7bqu22BqfXKKkcBoKOrLfV6gEOAc/8I3I9MGzSbK1eObFK53ns1OApfpEwDNRcv8EJ1/1ld7/9BUf7cVPwtVUQStBBV36YgFif1g2LdiS9alYN1qJbWI+1KXPJ77zNzUAR+tJ4RRUu/MW3HKnGtO/7VH6hoZuikAMwA9KO3xjyoyw16npja5yP5Uo90BmE/WylA7yWvZs4nKS8wF+i/ql8PaeIFcRHCR1ltOTBMJxQPGy3qB19ROBM6LtbI580hPJ8Kq0ZajPhQQxEeKYPvyV77lWgHxdnCpojcPEh2ycdVmXz9CJnnPVPo8dCvcItDDWbo1RzMXy4IM3HTnfYXJc4NO9W5KAST7sU4fjdegpeEYzfbpp+JNNxzfqPOzR/7/rRyRXlz/fNR1abtbF/NLJB+DK0ogQ1Wwk+WuDd72FTrSh7re20c/oow701URi3uQXS1mMsT6j3tvXb5DvR7WEukGIkkGgfohc+fwp+eSRl+dhtQylzvbaGaZS8emKuGsutJrenHp3Wex5uBczieE5rgjjlE3tO1YW7urXCcJnCR4dKqeXaA0zi1tibND9eMaJ4B3+nq1vAr/U+YPHSyIUvIkS99ubBsnug=
  on:
    tags: true
    repo: tastee/tastee-npm
